CREATE TABLE IF NOT EXISTS genre (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa_rating (
    rating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    rating_id INT,
    CONSTRAINT fk_rating_id FOREIGN KEY (rating_id) REFERENCES mpa_rating
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT,
    genre_id INT,
    CONSTRAINT fk_genre_film_id FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE,
    CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genre
);

CREATE TABLE IF NOT EXISTS user_friend_request (
    user_id BIGINT,
    friend_id BIGINT,
    status VARCHAR,
    CONSTRAINT fk_friends_user_id FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE,
    CONSTRAINT fk_friends_friend_id FOREIGN KEY (friend_id) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_likes (
    user_id BIGINT,
    film_id BIGINT,
    CONSTRAINT fk_likes_film_id FOREIGN KEY (film_id) REFERENCES film ON DELETE CASCADE,
    CONSTRAINT fk_likes_user_id FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE
);